### ISSUE TITLE
Link to the raw cityIOBackEnd

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO_Frontend#2]
We use to have a direct link to the table that are actually sending on the front end, i think it was useful

https://cityscope.github.io/CS_CityIO_Frontend/ this is now sending to the github backend I think it was better when it goes directly to the 
https://cityio.media.mit.edu/api/

I guees it's work in progress but maybe the square that shoes the different table (showing applet...) coudl be at some point the back end (if we redesign a bit it)

**Comment by RELNO** [comment]
> I guees it's work in progress but maybe the square that shoes the different table (showing applet...) coudl be at some point the back end (if we redesign a bit it)

Exactly my plans, will update soonish

**Comment by RELNO** [comment]
<img width="374" alt="screen shot 2018-06-19 at 10 32 46" src="https://user-images.githubusercontent.com/14296774/41604016-30aa9ab2-73ac-11e8-9592-5b52506dc40c.png">

Done, will be live in next production cycle.

**Comment by agrignard** [comment]
Nice!
Just has a good github habit I would close the issue as soon as it s commited

**Comment by agrignard** [comment]
A cool thing to do is to write 
'''
Fixes #XX 
''' 
in the commit messages it will automatically close the issue for you at the same time of the commit

**Comment by RELNO** [comment]
Cool tip!
It was committed before closing: https://github.com/CityScope/CS_CityIO_Frontend/commit/1fe8730f575aedffeade8058a20dc24fa98aee4c
Production ['live'] version is not updating in every commit.

**Comment by agrignard** [comment]
"Production ['live'] version is not updating in every commit." what do you mean? AS soon as the .js is modify it should be "visible" no? Do you have a kind a script that push every N commit?

**Comment by RELNO** [comment]
'Commits' apply to source code [`source`]. Production is [`dist`] code which is complied. compiling doesn't happen so often as commits of minor fixes. See more here: 
https://stackoverflow.com/questions/22842691/what-is-the-meaning-of-the-dist-directory-in-open-source-projects/22844164

The JS is indeed there, but the server is not running from source.

**Comment by agrignard** [comment]
Ok got it! A kind of nighly build
