### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_CityIO_Frontend#6]
Hi,
I deployed the master version locally and installed it using parcel.
Not sure what is going wrong here but when i open localhost:1234 the firefox dev tool yells: 
"ReferenceError: regeneratorRuntime is not defined" 

i'm not really sure of what it does mean, but i found a babel problem link: https://github.com/babel/babel/issues/5085#issuecomment-363242788 suggesting i should try to modify my .babelrc. (or our .babelrc ;) ?)  any advise/idea please?

**Comment by RELNO** [comment]
Usually ReferenceError: regeneratorRuntime is not defined" its async function that is missing the babel conversion. Try this:
https://github.com/babel/babel/issues/5085#issuecomment-374903233

**Comment by tuxun** [comment]
I tried to npm install babel-plugin-transform-runtime (I found a clue in deploy.md) and npm install generator-runtime which seems worked well, and my .babelrc is already as in your comment. Is it possible it misses an import somewhere (main.js?) or that the point to define it in babelrc? :)

ps: after that: is parcel build index.html required or parcel index.html is enough?

**Comment by tuxun** [comment]
i found it! add import 'babel-polyfill' in script/main.js (from https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined/36821986#36821986 linked from the issue you linked and i had read too fast) thx ( i may be will try to reproduce and make a PR later with updated babelrc and scripts/main.js)

**Comment by RELNO** [comment]
@tuxun great -- any documentation amendments you'd suggest?

**Comment by tuxun** [comment]
currently im not sure if the babelrc or the import in main.js did the job, i only discover babel and parcel. 
given i did parcel build index.html (which lasted 25seconds long) then parcel index.html (which also latest 25seconds long, instead of the previous 5second before modification) i think the total fix needs the both parcel steps (+ previously fixed babelrc and main.js )

**Comment by RELNO** [comment]
@tuxun trying to replicate your issue, but I did not see the babelIrc nor the long parce build problems on my end. Could you verify using updated NPM/parcel? Also can you make sure you're `sudo` your npm installs [to make sure packages are not facing access issues]

**Comment by tuxun** [comment]
from https://github.com/CityScope/CS_CityScopeJS_Tables/blob/346746def31f355a557481e0992897c2625c28b4/CSjs_WALK/scripts/index.js#L32
```
//fixes Uncaught ReferenceError: regeneratorRuntime is not defined
import "babel-polyfill";
```
so probably just the import did the job in my case. 

Long parcel build isnt a problem, I just meant that how i understood parcel build index.html was actually needed before do parcel index.html. 

parcel index.html does not call parcel build index.html, that maybe could be added to build note, i wasn't sure of what to do after I added the import, was this parcel build command needed or could parcel index.html rebuild all? now i know or I misunderstand something ;)  )

**Comment by RELNO** [comment]
> Long parcel build isn't a problem, I just meant that how i understood parcel build index.html was actually needed before do parcel index.html.

not from my experience - `parcel build` is for production, `parcel index.html` is for testing and HMR.
As for the rest, I suggest doing some more digging into parcel testing process:   
https://parceljs.org/getting_started.html
Let me know if there are other issues. 
Closing otherwise.

**Comment by tuxun** [comment]
i tried from scratch again, andagain missed smthing like an import "babel-polyfill"; in the main.js for get rid of this "ReferenceError: regeneratorRuntime is not defined"

**Comment by RELNO** [comment]
can you PR this? I haven't been able to reproduce this issue

**Comment by tuxun** [comment]
Please keep this issue closed, I again solved this problem, I'm again not sure of how :/ . (i reinstalled node, npm, and parcelbundler using sudo instead of my root account, now it works, maybe it was a permission issue). i use node 10.13 under ubuntu 18.10 and firefox 63. i had to install node from https://github.com/nodesource/distributions/blob/master/README.md  cause the version in the depot was missing modules (node-gyp if i  remember) do you see something wrong? :)
