### ISSUE TITLE
duplicated table name but different table (characters case "problem")

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_CityIO_Frontend#8]
at the moment there is a cityscopejs and a CityScopeJS table, personnally i like when file path are case sensitive, but for table names its another story. in dataviz apps code, i prefer String basename="cityjs"; and String basename="cityJS"; acting the same manner

**Comment by RELNO** [comment]
good idea, an auto-lowercaseing function will do the trick I guess. Care to try and PR ?

**Comment by tuxun** [comment]
I DO :) but maybe its more a backend job (damn i'm then on the wrong repo)? 

I see three place where we could lowercase the needed value(s): 
- the filename of the json in the post request, which update file to the server in the frontend
- the json value "name" 
- the API action corresponding to "get table" (aka /api/table/tablename)

Given it would sort of check if the values are lowercase, probably it would be clever to do it server side. 
That kinda secure the fact inputs are stocked in lowercase, even if there is legotizer not up to date with master version. 

After that, I hope the two actual tables are not too important, cause if they doesnt change their settings the day patch will be deployed, they will both users of "cityscope" and Cityscope" start to use the same json, leading to a bent space-time in the lego part of our multiverse ;)
